project_name: temp-api
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Stian Frøystein
    description: Temp API.
    homepage: https://github.com/stianfro/temp-api
    license: MIT
    formats:
      - deb
      - rpm
      - apk
